name: lepipeline
on: 
    push:
        branches:
          ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: npm run build
    test-job:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run dev
    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo "hello World!"
