name: lepipeline
on: 
    push:
        branches:
          ["main"]
jobs:
            build:
              runs-on: ubuntu-latest
          
              steps:
              - name: Checkout code
                uses: actions/checkout@v2
          
              - name: Cache node modules
                uses: actions/cache@v2
                with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
              - name: Use Node.js 14.x
                uses: actions/setup-node@v2
                with:
                  node-version: '14.x'
          
              - name: Install Dependencies
                run: npm install
          
              - name: Run Development Server
                run: npm run dev
          
    test-job:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm run dev
    deploy-job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo "hello World!"
